name: Kanban Automation

on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - edited
      - closed

jobs:
  move-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Move Issues on Kanban
        uses: alex-page/github-project-automation-plus@v0.6.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          project: GitHub Actions Kanban
          action: update
          column: |
            Ready: To Do
            In Progress: In Progress
            Done: Done
