name: Move Issues on Kanban Based on Comments

on:
  issue_comment:
    types:
      - created

jobs:
  move-issues:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: List all projects for debugging
    - name: List projects
      run: gh project list --owner "@me" --format json | jq
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Debug Project Information and Columns
    - name: Debug Project Columns
      run: gh project view PVT_kwHOCtxenM4As1ms --format json --owner "@me" | jq '.columns'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Move issues based on comment content (Done)
    - name: Move Issues to 'Done'
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      if: ${{ github.event.comment.body contains 'Done' }}
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        project_id: "PVT_kwHOCtxenM4As1ms"
        user: "@me"
        resource_node_id: ${{ github.event.issue.node_id }}
        move_related_issues: true
        status_value: "Done"
        operation_mode: status

    # Step 5: Move issues based on comment content (In Progress)
    - name: Move Issues to 'In Progress'
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      if: ${{ github.event.comment.body contains 'In progress' }}
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        project_id: "PVT_kwHOCtxenM4As1ms"
        user: "@me"
        resource_node_id: ${{ github.event.issue.node_id }}
        move_related_issues: true
        status_value: "In Progress"
        operation_mode: status
