name: Move Issues on Kanban Based on Comments

on:
  issue_comment:
    types:
      - created

jobs:
  move-issues:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: List all projects for debugging
    - name: List projects
      run: gh project list
      env:
        GH_TOKEN: ${{ secrets.aish }}

    # Step 3: Debug Project Information and Fetch Columns
    - name: Debug Project Information and Columns
      run: |
        gh project view PVT_kwHOCtxenM4As1ms --format json --owner "@me" | jq -r '.columns'
      env:
        GH_TOKEN: ${{ secrets.aish }}

    # Step 4: Move issues based on comment content (Done)
    - name: Move Issues to 'Done'
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created' && contains(github.event.comment.body, 'Done') }}
      with:
        gh_token: ${{ secrets.aish }}
        project_id: "PVT_kwHOCtxenM4As1ms" # Full project ID
        user: '@me' # Replace with your username or keep '@me' for personal projects
        resource_node_id: ${{ github.event.issue.node_id }}
        move_related_issues: true
        status_value: "Done" # Matches the column name on your board

    # Step 5: Move issues based on comment content (In Progress)
    - name: Move Issues to 'In Progress'
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created' && contains(github.event.comment.body, 'In progress') }}
      with:
        gh_token: ${{ secrets.aish }}
        project_id: "PVT_kwHOCtxenM4As1ms" # Full project ID
        user: '@me' # Replace with your username or keep '@me'
        resource_node_id: ${{ github.event.issue.node_id }}
        move_related_issues: true
        status_value: "In Progress" # Matches the column name on your board
