name: Move Issues on Kanban Based on Comments

on:
  issue_comment:
    types:
      - created

jobs:
  move-issues:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: List all projects for debugging
    - name: List projects
      run: gh project list --owner "@me" --format json | jq
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Fetch Project Details
    - name: Fetch Project Columns
      id: fetch_project
      run: |
        gh project view PVT_kwHOCtxenM4As1ms --format json --owner "@me" | jq
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Fetch Issue Node ID
    - name: Get Issue Node ID
      id: fetch_node_id
      run: echo "NODE_ID=$(gh issue view ${{ github.event.issue.number }} --json node_id --jq '.node_id')" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 5: Move Issue to 'Done'
    - name: Move Issue to 'Done'
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      if: ${{ github.event.comment.body && contains(github.event.comment.body, 'Done') }}
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        project_id: "PVT_kwHOCtxenM4As1ms"
        user: "@me"
        resource_node_id: ${{ env.NODE_ID }}
        move_related_issues: true
        status_value: "Done"
        operation_mode: status
